;Somma elementi di un array
SECTION .DATA
X DD 12,4,2,-6,-5,1
N DD ($-X)/4

SECTION .BSS
S RESD 1		;PER MEMORIZZARE LA SOMMA

SECTION .TEXT
GLOBAL START
START:
	MOV EAX, 0	;INIZIALIZZIAMO EAX DOVE SALVEREMO LA SOMMA
	MOV ESI, 0 	;INIZIALIZZIAMO ESI DOVE SALVEREMO L'INDICE
	
CICLO:
	CMP ESI, N ;(i<n)?
	JGE FINE
	ADD EAX, [X+4*ESI]; ADD <SORG><DEST> --> <SORG> = <SORG>+>DEST>
	INC ESI 	;INDICE+=1
	JMP CICLO
FINE
	MOV [S], EAX	;LA SOMMA VIENE CARICATA IN EAX
	EXIT 0
	
	

