; SE IL PRIMO NUMERO È MINORE DEL SECONDO PRINT IL SECONDO NUMERO
SECTION .DATA
	X DD 20
	Y DD 30
	
SECTION .TEXT
	
GLOBAL START
START:
	MOV EAX, [X]	
	MOV EBX, [Y]
	SUB EAX, EBX  ;20-30
	JNS FINE 
	PRINTD EBX	; STAMPA 30 CIOÈ IL NOSTRO VALORE Y
FINE:
	EXIT 0
	
