; SE IL PRIMO NUMERO È MINORE DEL SECONDO PRINT IL SECONDO NUMERO
SECTION .DATA
	X DD 20
	Y DD 30
	
SECTION .TEXT
	
GLOBAL START
START:
	MOV EAX,[X]
	MOV EBX,[Y]
	CMP EAX,EBX ;EFFETTUA LA COMPARAZIONE TRA I DUE VALORI
	JGE ELSE
	PRINTD EAX
	JMP END		;SALTA A PRESCINDERE FA QUELLO CHE VUOLE

ELSE:
	PRINTD EBX
END:
	EXIT 0
